version: "3.7"

services:
  accesslog:
    image: diamol/ch09-access-log
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: 100M
    networks:
      - app-net
# 로그 API

  iotd:
    image: diamol/ch09-image-of-the-day
    ports:
      - 8088:80
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 200M
    networks:
      - app-net
# 프론트 엔드 웹페이지

  image-gallery:
    image: diamol/ch09-image-gallery
    ports:
      - 80:80
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.75"
          memory: 75M
    networks:
      - app-net
# NASA API

networks:
  app-net:
    name: image-gallery-prod
# 네트워크 정의